# Generated by Django 2.2.5 on 2019-10-25 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('is_group_chat', models.BooleanField(default=False)),
                ('topic', models.CharField(blank=True, max_length=64)),
                ('last_message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('content', models.TextField(default='')),
                ('added_at', models.DateTimeField()),
                ('msg_chat_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chats.Chat')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_profile.User')),
            ],
        ),
    ]
