# Generated by Django 2.2.5 on 2019-10-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('nick', models.CharField(default='', max_length=64)),
                ('avatar', models.CharField(default='', max_length=256)),
            ],
        ),
    ]
