# Generated by Django 2.2.5 on 2019-10-25 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('new_messages', models.BooleanField(default=False)),
                ('chat_id', models.ManyToManyField(to='chats.Chat')),
                ('last_read_message_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='chats.Message')),
            ],
        ),
    ]
